apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "app-chart.fullname" . }}
  labels:
{{ include "app-chart.labels" . | indent 4 }}
  annotations:
    helm.sh/hook: "post-upgrade, post-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
spec:
  minAvailable: {{ .Values.pdbMinAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app-chart.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  minAvailable: {{ .Values.pdbMinAvailable }}
